version: '3.8'

services:
  db:
    image: postgres:14
    container_name: crm_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: goodcom_crm
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: crm_web
    volumes:
      - .:/app
    environment:
      - DATABASE_URL=postgresql://postgres:1234@db:5432/goodcom_crm
    ports:
      - "8000:8000"
    depends_on:
      - db

volumes:
  postgres_data:
