# Generated by Django 5.1.3 on 2024-11-29 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Название задачи"),
                ),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание задачи"),
                ),
                (
                    "due_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Крайний срок"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "Новая"),
                            ("In Progress", "В процессе"),
                            ("Completed", "Выполнена"),
                        ],
                        default="New",
                        max_length=50,
                        verbose_name="Статус задачи",
                    ),
                ),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Исполнитель",
                    ),
                ),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Создатель задачи",
                    ),
                ),
            ],
        ),
    ]
