# Generated by Django 5.1.3 on 2024-12-01 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="due_time",
            field=models.TimeField(
                blank=True, null=True, verbose_name="Крайний срок (время)"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="due_date",
            field=models.DateField(
                blank=True, null=True, verbose_name="Крайний срок (дата)"
            ),
        ),
    ]
