# Generated by Django 5.1.3 on 2024-12-01 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0002_task_due_time_alter_task_due_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата выполнения"
            ),
        ),
    ]
