# Generated by Django 5.1.3 on 2024-12-01 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0003_task_completed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="completed_at",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата завершения"
            ),
        ),
    ]
